watcher:
    build: ./var/dockerfile/go/
    working_dir: /usr/src/watcher
    volumes:
        - .:/usr/src/watcher
    command: sleep 123456789
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>>  code and test fixed
    links:
        - api:api
api:
    build: ./var/dockerfile/go/
    working_dir: /usr/src/api
    volumes:
        - .:/usr/src/api
    command: sleep 123456789
    expose:
        - "8000"
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> add PingPoller_test.go
=======
>>>>>>>  code and test fixed
=======
>>>>>>> fe35ab3749b7451f789da23b18b4944146380c19
