watcher:
    build: ./var/dockerfile/go/
    ports:
        - "8000:8000"
    working_dir: /usr/src/watcher
    volumes:
        - .:/usr/src/watcher
    command: sleep 123456789
bd:
    build: ./var/dockerfile/postgreSql