watcher:
    build: ./var/dockerfile/go/
    ports:
        - "8000:8000"
    working_dir: /usr/src/watcher
    volumes:
        - .:/usr/src/watcher
    command: sleep 123456789
<<<<<<< HEAD
    links:
        - api:api
api:
    build: ./var/dockerfile/go/
    working_dir: /usr/src/api
    volumes:
        - .:/usr/src/api
    command: sleep 123456789
    expose:
        - "8000"
=======
>>>>>>> add PingPoller_test.go
